# cmake/BuildISAL.cmake
# -------------------------------------------------------------------
# External Project Wrapper for Intel ISA-L (Autotools to CMake Bridge)
# -------------------------------------------------------------------

include(ExternalProject)

set(ISAL_SRC_DIR "${CMAKE_CURRENT_SOURCE_DIR}/third_party/isa-l")
set(ISAL_INSTALL_DIR "${CMAKE_CURRENT_BINARY_DIR}/third_party/isa-l/install")

# Define where the shared library will be generated by autotools
if(WIN32)
    message(FATAL_ERROR "ISA-L compilation via submodule is only supported on POSIX.")
else()
    set(ISAL_SHARED_LIB "${ISAL_INSTALL_DIR}/lib/libisal.so")
endif()

# ===================================================================
# Pre-flight Check: Ensure nasm assembler is available on the Host
# ===================================================================
# ISA-L heavily relies on nasm for processing its high-performance 
# AVX512 and AVX2 vectorized assembly routines.
find_program(NASM_EXECUTABLE nasm)
if(NOT NASM_EXECUTABLE)
    message(FATAL_ERROR "CRITICAL ERROR: 'nasm' assembler not found! "
                        "ISA-L cannot compile its specialized SIMD layouts without it. "
                        "Please run 'sudo apt install nasm' or 'sudo dnf install nasm' first.")
endif()

# ===================================================================
# Core Magic: Trigger autotools pipeline inside CMake build stage
# ===================================================================
ExternalProject_Add(isal_ext
    SOURCE_DIR ${ISAL_SRC_DIR}
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/third_party/isa-l

    # Strip stale configure artifacts so re-configuration always works
    CONFIGURE_COMMAND sh -c "cd '${ISAL_SRC_DIR}' && rm -f config.status Makefile config.log 2>/dev/null && ./autogen.sh"
    # configure runs from the build dir (ExternalProject's default CWD) so Makefile lands there
    COMMAND "${ISAL_SRC_DIR}/configure" "CC=${CMAKE_C_COMPILER_LAUNCHER} ${CMAKE_C_COMPILER}" "--prefix=${ISAL_INSTALL_DIR}" "--disable-static" "--enable-shared" "CFLAGS=-O3 -fPIC"

    BUILD_COMMAND ${CMAKE_MAKE_PROGRAM}
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install

    # Capture verbose autotools output to log files for a clean CMake-style display
    LOG_CONFIGURE ON
    LOG_BUILD ON
    LOG_INSTALL ON

    # Ensure CMake monitors these outputs to avoid redundant compilations
    BUILD_BYPRODUCTS ${ISAL_SHARED_LIB}
)

# Pre-create the install include dir to satisfy CMake's IMPORTED target validation
file(MAKE_DIRECTORY "${ISAL_INSTALL_DIR}/include")

# Create an imported shared library target for your storage engine to consume
add_library(isal SHARED IMPORTED GLOBAL)
add_dependencies(isal isal_ext)

# Export include directories and shared library paths
set_target_properties(isal PROPERTIES
    IMPORTED_LOCATION ${ISAL_SHARED_LIB}
    INTERFACE_INCLUDE_DIRECTORIES "${ISAL_INSTALL_DIR}/include"
)

# Expose global variable to mark availability
set(HAVE_ISA_L TRUE CACHE INTERNAL "")
